// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_f3Ifq4zngiYDsWR2A6zPMR5aF6dmyP4',
    appId: '1:467856591085:web:a93831a1b12043b921e4e4',
    messagingSenderId: '467856591085',
    projectId: 'dinesh-project-62139',
    authDomain: 'dinesh-project-62139.firebaseapp.com',
    databaseURL: 'https://dinesh-project-62139-default-rtdb.firebaseio.com',
    storageBucket: 'dinesh-project-62139.appspot.com',
    measurementId: 'G-PE0M2JVR1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWVY34gThZ0MoTnzCwmA-QSEFCQjCPQ4',
    appId: '1:467856591085:android:8199343605a407f021e4e4',
    messagingSenderId: '467856591085',
    projectId: 'dinesh-project-62139',
    databaseURL: 'https://dinesh-project-62139-default-rtdb.firebaseio.com',
    storageBucket: 'dinesh-project-62139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWomUhYp0WaPYsFMUsbSHJKy-i98hfszU',
    appId: '1:467856591085:ios:411cc22e6b93e0e221e4e4',
    messagingSenderId: '467856591085',
    projectId: 'dinesh-project-62139',
    databaseURL: 'https://dinesh-project-62139-default-rtdb.firebaseio.com',
    storageBucket: 'dinesh-project-62139.appspot.com',
    iosBundleId: 'com.example.dineshProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWomUhYp0WaPYsFMUsbSHJKy-i98hfszU',
    appId: '1:467856591085:ios:3765a36762052e4021e4e4',
    messagingSenderId: '467856591085',
    projectId: 'dinesh-project-62139',
    databaseURL: 'https://dinesh-project-62139-default-rtdb.firebaseio.com',
    storageBucket: 'dinesh-project-62139.appspot.com',
    iosBundleId: 'com.example.dineshProject.RunnerTests',
  );
}
